return {
  [1] = {
    id = 1,
    diff_name = "触发两队敌人的战斗时长缩放",
    enum_name = "copy_battle_time_factor",
    data = "1.5",
  },
  [2] = {
    id = 2,
    diff_name = "小破生命值上限",
    enum_name = "BL_xiaopo_top",
    data = "0.75",
  },
  [3] = {
    id = 3,
    diff_name = "小破生命值下限",
    enum_name = "BL_xiaopo_down",
    data = "0.5",
  },
  [4] = {
    id = 4,
    diff_name = "中破生命值上限",
    enum_name = "BL_zhongpo_top",
    data = "0.5",
  },
  [5] = {
    id = 5,
    diff_name = "中破生命值下限",
    enum_name = "BL_zhongpo_down",
    data = "0.25",
  },
  [6] = {
    id = 6,
    diff_name = "大破生命值上限",
    enum_name = "BL_dapo_top",
    data = "0.25",
  },
  [7] = {
    id = 7,
    diff_name = "大破生命值下限",
    enum_name = "BL_dapo_down",
    data = "0",
  },
  [8] = {
    id = 8,
    diff_name = "中破攻击下降参数",
    enum_name = "BL_zhongpo_attack_decline",
    data = "0.5",
  },
  [9] = {
    id = 9,
    diff_name = "大破攻击下降参数",
    enum_name = "BL_dapo_attack_decline",
    data = "0.25",
  },
  [10] = {
    id = 10,
    diff_name = "战术胜利B战果条参数1",
    enum_name = "battle_over_b1",
    data = "2.5",
  },
  [11] = {
    id = 11,
    diff_name = "战术胜利B战果条参数2",
    enum_name = "battle_over_b2",
    data = "3",
  },
  [12] = {
    id = 12,
    diff_name = "战术败北C战果条参数1",
    enum_name = "battle_over_c1",
    data = "2.5",
  },
  [13] = {
    id = 13,
    diff_name = "战术败北C战果条参数2",
    enum_name = "battle_over_c2",
    data = "3",
  },
  [14] = {
    id = 14,
    diff_name = "败北伤害参数",
    enum_name = "battle_over_d_dmg",
    data = "0.0005",
  },
  [15] = {
    id = 15,
    diff_name = "败北战果条参数",
    enum_name = "battle_over_d1",
    data = "0.75",
  },
  [16] = {
    id = 16,
    diff_name = "败北战果条参数",
    enum_name = "battle_over_e1",
    data = "0.75",
  },
  [17] = {
    id = 17,
    diff_name = "侦察机技能CD",
    enum_name = "detect_air_cd",
    data = "15",
  },
  [18] = {
    id = 18,
    diff_name = "侦察机视野范围",
    enum_name = "detect_air_view_radius",
    data = "20",
  },
  [19] = {
    id = 19,
    diff_name = "疲劳效果出发百分比",
    enum_name = "weary_effect_trigger_percent",
    data = "0.5",
  },
  [20] = {
    id = 20,
    diff_name = "疲劳效果触发buffID",
    enum_name = "weary_effect_trigger_debuff",
    data = "9000",
  },
  [21] = {
    id = 21,
    diff_name = "疲劳度到达上限时强制切换至原速档位控制百分比",
    enum_name = "weary_effect_force2source_percent",
    data = "0.3",
  },
  [22] = {
    id = 22,
    diff_name = "舰娘模型一般半径",
    enum_name = "ship_radius",
    data = "1",
  },
  [23] = {
    id = 23,
    diff_name = "战舰落下距离1，无法参与索敌的航空攻击与侦察机技能",
    enum_name = "ship_lose_distance1",
    data = "10",
  },
  [24] = {
    id = 24,
    diff_name = "战舰落下距离2，无法参与作战",
    enum_name = "ship_lose_distance2",
    data = "20",
  },
  [25] = {
    id = 25,
    diff_name = "战斗阶段档位速度切换时间",
    enum_name = "battle_speed_exchange_time",
    data = "1",
  },
  [26] = {
    id = 26,
    diff_name = "战斗阶段一杯速度触发BuffID",
    enum_name = "battle_speed_a_cup_buff",
    data = "9001",
  },
  [27] = {
    id = 27,
    diff_name = "战斗使用的摄像机路径名",
    enum_name = "battle_camera_normal_path",
    data = "shot/enter_logic01",
  },
  [28] = {
    id = 28,
    diff_name = "进入据点开场的摄像机ID",
    enum_name = "battle_camera_enter_logic",
    data = "1",
  },
  [29] = {
    id = 29,
    diff_name = "进入据点待机情况下左侧摄像机ID",
    enum_name = "battle_camera_left_logic_idle",
    data = "100",
  },
  [30] = {
    id = 30,
    diff_name = "进入战斗开场的摄像机ID",
    enum_name = "battle_camera_enter_battle",
    data = "10",
  },
  [31] = {
    id = 31,
    diff_name = "进入战斗待机情况下左侧摄像机ID",
    enum_name = "battle_camera_left_idle",
    data = "200",
  },
  [32] = {
    id = 32,
    diff_name = "进入战斗待机情况下右侧摄像机ID",
    enum_name = "battle_camera_right_idle",
    data = "300",
  },
  [33] = {
    id = 33,
    diff_name = "船只脚底圆圈资源路径，绿",
    enum_name = "battle_ship_circle_green",
    data = "effects/prefabs/zd_ui/eff3d_sail_feetring_green",
  },
  [34] = {
    id = 34,
    diff_name = "船只脚底圆圈资源路径，红",
    enum_name = "battle_ship_circle_red",
    data = "effects/prefabs/zd_ui/eff3d_sail_feetring_red",
  },
  [35] = {
    id = 35,
    diff_name = "近距离",
    enum_name = "BL_Near",
    data = "150",
  },
  [36] = {
    id = 36,
    diff_name = "中距离",
    enum_name = "BL_Middle",
    data = "260",
  },
  [37] = {
    id = 37,
    diff_name = "远距离",
    enum_name = "BL_Far",
    data = "350",
  },
  [38] = {
    id = 38,
    diff_name = "超远距离",
    enum_name = "BL_SFar",
    data = "500",
  },
  [39] = {
    id = 39,
    diff_name = "我方索敌半径",
    enum_name = "BL_PlayerSearchRadius",
    data = "30",
  },
  [40] = {
    id = 40,
    diff_name = "敌方索敌半径",
    enum_name = "BL_EnemySearchRadius",
    data = "10",
  },
  [41] = {
    id = 41,
    diff_name = "战场内舰队最小间隔",
    enum_name = "BL_FleetMinInterval",
    data = "40",
  },
  [42] = {
    id = 42,
    diff_name = "舰队变阵最大限制距离",
    enum_name = "BL_FormLimitDistance",
    data = "15",
  },
  [43] = {
    id = 43,
    diff_name = "舰队变速持续时间（毫秒）",
    enum_name = "BL_FleetChangeSpeedTime",
    data = "1000",
  },
  [44] = {
    id = 44,
    diff_name = "疲劳舰队恢复百分比",
    enum_name = "BL_FatiguePercent",
    data = "0.2",
  },
  [45] = {
    id = 45,
    diff_name = "舰娘落下后追赶速度系数",
    enum_name = "BL_ShipFallDownSpeedFac",
    data = "0.8",
  },
  [46] = {
    id = 46,
    diff_name = "舰队冲刺时的速度系数",
    enum_name = "BL_FleetSprintSpeecFac",
    data = "1",
  },
  [47] = {
    id = 47,
    diff_name = "舰队冲刺持续时间（毫秒）",
    enum_name = "BL_FleetSprintDurationTime",
    data = "1000",
  },
  [48] = {
    id = 48,
    diff_name = "单场战斗鱼雷最大使用次数",
    enum_name = "BL_BattleTorpedoMaxNum",
    data = "2",
  },
  [49] = {
    id = 49,
    diff_name = "疲劳值A最大值",
    enum_name = "BL_FatigueAMax",
    data = "100",
  },
  [50] = {
    id = 50,
    diff_name = "疲劳值B最大值",
    enum_name = "BL_FatigueBMax",
    data = "50",
  },
  [51] = {
    id = 51,
    diff_name = "阵型内间距",
    enum_name = "BL_ShipInterval",
    data = "4.2",
  },
  [52] = {
    id = 52,
    diff_name = "航空侦察动画延迟时间",
    enum_name = "BL_AerialReconnaissanceDelay",
    data = "4",
  },
  [53] = {
    id = 53,
    diff_name = "航空攻击动画延迟时间",
    enum_name = "BL_AirAttackDelay",
    data = "4",
  },
  [54] = {
    id = 54,
    diff_name = "航空侦察横向最大限制距离",
    enum_name = "BL_ARHorizontalLimitLength",
    data = "200",
  },
  [55] = {
    id = 55,
    diff_name = "航空侦察横向最大限制转角",
    enum_name = "BL_ARHorizontalLimitEuler",
    data = "30",
  },
  [56] = {
    id = 56,
    diff_name = "航空侦察转向角度",
    enum_name = "BL_ARRotateEuler",
    data = "90",
  },
  [57] = {
    id = 57,
    diff_name = "航空侦察飞行速度",
    enum_name = "BL_AerialReconnaissanceSpeed",
    data = "35",
  },
  [58] = {
    id = 58,
    diff_name = "航空侦察转向角速度",
    enum_name = "BL_AerialReconnaissanceEulerSpeed",
    data = "90",
  },
  [59] = {
    id = 59,
    diff_name = "航空攻击圈半径",
    enum_name = "BL_AerialAttackLimitLength",
    data = "17",
  },
  [60] = {
    id = 60,
    diff_name = "特殊航空攻击圈半径",
    enum_name = "BL_AdvanceAerialAttackLimitLength",
    data = "17",
  },
  [61] = {
    id = 61,
    diff_name = "航空攻击飞行速度",
    enum_name = "BL_AerialAttackSpeed",
    data = "30",
  },
  [62] = {
    id = 62,
    diff_name = "巡逻路径点安全距离",
    enum_name = "BL_FleetPatrolRouteLimitLength",
    data = "2",
  },
  [63] = {
    id = 63,
    diff_name = "舰队发现敌舰扇形角度的半值",
    enum_name = "BL_FindEnemyHalfEuler",
    data = "60",
  },
  [64] = {
    id = 64,
    diff_name = "舰队发现敌舰扇形半径",
    enum_name = "BL_FindEnemyRadius",
    data = "100",
  },
  [65] = {
    id = 65,
    diff_name = "舰队侦察机发现敌舰最大距离",
    enum_name = "BL_PlaneFindEnemyRadius",
    data = "20",
  },
  [66] = {
    id = 66,
    diff_name = "舰队追踪最远距离",
    enum_name = "BL_TrackDisMax",
    data = "120",
  },
  [67] = {
    id = 67,
    diff_name = "舰队追踪最远相对距离",
    enum_name = "BL_TrackFleetDisMax",
    data = "150",
  },
  [68] = {
    id = 68,
    diff_name = "AI技能释放判断的间隔CD（单位毫秒）",
    enum_name = "BL_AISkillCheckReleaseCD",
    data = "2000",
  },
  [69] = {
    id = 69,
    diff_name = "舰队主炮能量最大值",
    enum_name = "BL_ShipMaxPower",
    data = "100",
  },
  [70] = {
    id = 70,
    diff_name = "副炮内置CD（秒）",
    enum_name = "BL_SecondGunCD",
    data = "0.2",
  },
  [71] = {
    id = 71,
    diff_name = "索敌地图横向百分比",
    enum_name = "BL_SearchMapXPercent",
    data = "0.5",
  },
  [72] = {
    id = 72,
    diff_name = "索敌地图纵向百分比",
    enum_name = "BL_SearchMapYPercent",
    data = "0.5",
  },
  [73] = {
    id = 73,
    diff_name = "主界面场景相机绕人旋转速度",
    enum_name = "Camera_Rotate_Speed",
    data = "0.1",
  },
  [74] = {
    id = 74,
    diff_name = "战斗时AI活动范围与战场范围距离（米）",
    enum_name = "BL_AIMoveDisWithBattleRange",
    data = "20",
  },
  [75] = {
    id = 75,
    diff_name = "最小伤害系数",
    enum_name = "BL_MinDamageRate",
    data = "0.1",
  },
  [76] = {
    id = 76,
    diff_name = "鱼雷最小伤害倍率",
    enum_name = "BL_TurpedoDamageRateMin",
    data = "1",
  },
  [77] = {
    id = 77,
    diff_name = "鱼雷最大伤害倍率",
    enum_name = "BL_TorpedoDamageRateMax",
    data = "1",
  },
  [78] = {
    id = 78,
    diff_name = "鱼雷最小伤害概率",
    enum_name = "BL_TorpedoDamageRateMinChance",
    data = "0.5",
  },
  [79] = {
    id = 79,
    diff_name = "鱼雷最大伤害概率",
    enum_name = "BL_TorpedoDamageRateMaxChance",
    data = "0.5",
  },
  [80] = {
    id = 80,
    diff_name = "暴击伤害倍率",
    enum_name = "BL_CritDamageRate",
    data = "0.5",
  },
  [81] = {
    id = 81,
    diff_name = "两舰齐射伤害加成",
    enum_name = "BL_2ShipMaingunDamageAdd",
    data = "0.03",
  },
  [82] = {
    id = 82,
    diff_name = "三舰齐射伤害加成",
    enum_name = "BL_3ShipMaingunDamageAdd",
    data = "0.05",
  },
  [83] = {
    id = 83,
    diff_name = "四舰齐射伤害加成",
    enum_name = "BL_4ShipMaingunDamageAdd",
    data = "0.1",
  },
  [84] = {
    id = 84,
    diff_name = "五舰齐射伤害加成",
    enum_name = "BL_5ShipMaingunDamageAdd",
    data = "0.15",
  },
  [85] = {
    id = 85,
    diff_name = "全舰齐射伤害加成",
    enum_name = "BL_6ShipMaingunDamageAdd",
    data = "0.2",
  },
  [86] = {
    id = 86,
    diff_name = "舰娘变阵逻辑最小间距",
    enum_name = "BL_ChangeFormMinShipDistance",
    data = "1",
  },
  [87] = {
    id = 87,
    diff_name = "舰队不可变阵限制距离",
    enum_name = "BL_ChangeFormLimitDistance",
    data = "3",
  },
  [88] = {
    id = 88,
    diff_name = "战场边缘特效",
    enum_name = "BATTLE_SIDE_WARNING",
    data = "effects/prefabs/eff3d_forbiddenzone_black",
  },
  [89] = {
    id = 89,
    diff_name = "战场靠近敌方预警特效",
    enum_name = "BATTLE_NEAR_WARNING",
    data = "effects/prefabs/eff3d_forbiddenzone_red",
  },
  [90] = {
    id = 90,
    diff_name = "我方舰队方向指示",
    enum_name = "FLEET_ARROW_GREEN",
    data = "effects/prefabs/zd_ui/eff3d_sail_arrowgreen",
  },
  [91] = {
    id = 91,
    diff_name = "敌方舰队方向指示",
    enum_name = "FLEET_ARROW_RED",
    data = "effects/prefabs/zd_ui/eff3d_sail_arrowred",
  },
  [92] = {
    id = 92,
    diff_name = "船只浪花",
    enum_name = "SHIP_SAIL_WATER",
    data = "effects/prefabs/eff3d_sailing_water_01",
  },
  [93] = {
    id = 93,
    diff_name = "主炮命中水花(废弃)",
    enum_name = "GUN_HIT_WATER",
    data = "effects/prefabs/eff3d_gun_misswater_01",
  },
  [94] = {
    id = 94,
    diff_name = "玩家鱼雷",
    enum_name = "PLAYER_TORPEDO_MODEL",
    data = "effects/prefabs/zd_ui/eff3d_torpedo_range_01",
  },
  [95] = {
    id = 95,
    diff_name = "敌方鱼雷",
    enum_name = "ENEMY_TORPEDO_MODEL",
    data = "effects/prefabs/zd_ui/eff3d_torpedo_rangeenemy_01",
  },
  [96] = {
    id = 96,
    diff_name = "鱼雷命中水花（废弃）",
    enum_name = "TORPEDO_HIT_WATER",
    data = "14",
  },
  [97] = {
    id = 97,
    diff_name = "鱼雷航行拖尾",
    enum_name = "TORPEDO_MOVE_SAIL_WATER",
    data = "16",
  },
  [98] = {
    id = 98,
    diff_name = "击沉气泡",
    enum_name = "SINK_BUBBLE",
    data = "26",
  },
  [99] = {
    id = 99,
    diff_name = "击沉炸弹",
    enum_name = "SINK_BOOM",
    data = "27",
  },
  [100] = {
    id = 100,
    diff_name = "击沉逻辑下沉速度",
    enum_name = "SIMPLE_DROP_SPEED",
    data = "0.5",
  },
  [101] = {
    id = 101,
    diff_name = "摄像机拉近完后的等待时间",
    enum_name = "CAMERA_ZOOM_IN_AT_DURATION",
    data = "0.6",
  },
  [102] = {
    id = 102,
    diff_name = "主炮或鱼雷命中震动屏幕时间",
    enum_name = "MAIN_GUN_OR_TORPEDO_SHAKE_CAMERA_DURATION",
    data = "0.3",
  },
  [103] = {
    id = 103,
    diff_name = "主炮敌人前的时间流逝变慢时间参数",
    enum_name = "skillAnimHitSlowTimeScale",
    data = "0.15",
  },
  [104] = {
    id = 104,
    diff_name = "主炮敌人前的时间流逝变慢时间",
    enum_name = "skillAnimHitSlowTime",
    data = "0.2",
  },
  [105] = {
    id = 105,
    diff_name = "鱼雷和航空攻击时间缩放参数",
    enum_name = "torpedoAndAirSkillAnimHitSlowTimeScale",
    data = "0.15",
  },
  [106] = {
    id = 106,
    diff_name = "鱼雷和航空攻击命中时间流逝变慢",
    enum_name = "torpedoAndAirSkilAnimHitSlowTime",
    data = "0.2",
  },
  [107] = {
    id = 107,
    diff_name = "鱼雷和航空攻击命中前时间开始变慢时间点",
    enum_name = "torpedoAndAirSkillAnimHitSlowTimeBeforeHit",
    data = "0.35",
  },
  [108] = {
    id = 108,
    diff_name = "技能动画过程中模拟的攻击方被击方距离",
    enum_name = "SKILL_ANIM_ATTACK_2_DEFENCE_DISTANCE",
    data = "200",
  },
  [109] = {
    id = 109,
    diff_name = "技能动画模拟移动速度",
    enum_name = "skillAnimSpeed",
    data = "6",
  },
  [110] = {
    id = 110,
    diff_name = "T有利主炮攻击系数",
    enum_name = "BL_TAdvantageAttackCoe",
    data = "1.2",
  },
  [111] = {
    id = 111,
    diff_name = "同航主炮攻击系数",
    enum_name = "BL_PositiveAttackCoe",
    data = "1",
  },
  [112] = {
    id = 112,
    diff_name = "反航主炮攻击系数",
    enum_name = "BL_ReverseAttackCoe",
    data = "1",
  },
  [113] = {
    id = 113,
    diff_name = "T不利主炮攻击系数",
    enum_name = "BL_TDisadvantageAttackCoe",
    data = "0.6",
  },
  [114] = {
    id = 114,
    diff_name = "标记检测敌方舰队与我方舰队距离",
    enum_name = "CEHCK_ENEMY_FLEET_DISTANCE",
    data = "100",
  },
  [115] = {
    id = 115,
    diff_name = "雷达圈覆盖范围",
    enum_name = "CHECK_ENEMY_FLEET_RADIU",
    data = "50",
  },
  [116] = {
    id = 116,
    diff_name = "侦察机侦查敌人一次增加信息阶段层数",
    enum_name = "SEARCH_FIND_ADD_STAGE",
    data = "3",
  },
  [117] = {
    id = 117,
    diff_name = "标记舰队自动增加信息阶层时间间隔",
    enum_name = "TICK_ADD_CURRENT_STAGE_SPACE",
    data = "5",
  },
  [118] = {
    id = 118,
    diff_name = "进入战斗玩家舰队计算距离的偏移距离",
    enum_name = "BL_PlayerEnterBattleDeltaLength",
    data = "30",
  },
  [119] = {
    id = 119,
    diff_name = "索敌阶段舰队移动自动转向最大限制距离",
    enum_name = "BL_SearchMoveAutoRotateLimitLength",
    data = "20",
  },
  [120] = {
    id = 120,
    diff_name = "战斗右摄切换远景时间",
    enum_name = "BD_RightCameraChangeDurationSpe",
    data = "0.2",
  },
  [121] = {
    id = 121,
    diff_name = "战斗右摄切换普通时间",
    enum_name = "BD_RightCameraChangeDuration",
    data = "0.4",
  },
  [122] = {
    id = 122,
    diff_name = "战斗右摄攻击警戒俯视系数N",
    enum_name = "BD_RightCameraEnemyWarningN",
    data = "1",
  },
  [123] = {
    id = 123,
    diff_name = "战斗右摄射程内平视系数N",
    enum_name = "BD_RightCameraInRangeN",
    data = "0.2",
  },
  [124] = {
    id = 124,
    diff_name = "陷阱圈间隔百分比",
    enum_name = "BL_TrapDistanceCoe",
    data = "1.2",
  },
  [125] = {
    id = 125,
    diff_name = "索敌阶段舰队视野(半径)",
    enum_name = "BD_SearchFleetViewRange",
    data = "40",
  },
  [126] = {
    id = 126,
    diff_name = "索敌舰队视野中心偏移距离",
    enum_name = "BD_SearchViewCenterPosDletaLength",
    data = "10",
  },
  [127] = {
    id = 127,
    diff_name = "PVE世界逻辑尺寸系数",
    enum_name = "BL_PVEWorldScale",
    data = "2.75",
  },
  [128] = {
    id = 128,
    diff_name = "主炮cutin持续时间（单位秒）",
    enum_name = "BL_MainGunCutinDuration",
    data = "4",
  },
  [129] = {
    id = 129,
    diff_name = "主炮cutin昼战触发概率（最大值1）",
    enum_name = "BL_MainGunCutinOdds",
    data = "0.037",
  },
  [130] = {
    id = 130,
    diff_name = "主炮cutin夜战触发概率（最大值1）",
    enum_name = "BL_MainGunCutinNightOdds",
    data = "0.1",
  },
  [131] = {
    id = 131,
    diff_name = "主炮cutin单次点击攻击值",
    enum_name = "BL_MainGunCutinDeltaMin",
    data = "3",
  },
  [132] = {
    id = 132,
    diff_name = "主炮cutin攻击最大值",
    enum_name = "BL_MainGunCutinDeltaMax",
    data = "75",
  },
  [133] = {
    id = 133,
    diff_name = "玩家索敌半径(PVP)",
    enum_name = "BL_PVP_PlayerSearchRadius",
    data = "50",
  },
  [134] = {
    id = 134,
    diff_name = "NPC索敌半径(PVP)",
    enum_name = "BL_PVP_EnemySearchRadius",
    data = "20",
  },
  [135] = {
    id = 135,
    diff_name = "索敌阶段舰队视野(半径)PVP用",
    enum_name = "BD_PVP_SearchFleetViewRange",
    data = "80",
  },
  [136] = {
    id = 136,
    diff_name = "索敌舰队视野中心偏移距离PVP用",
    enum_name = "BD_PVP_SearchViewCenterPosDletaLength",
    data = "30",
  },
  [137] = {
    id = 137,
    diff_name = "舰队冲刺时的速度系数(PVP)",
    enum_name = "BL_PVP_FleetSprintSpeecFac",
    data = "1",
  },
  [138] = {
    id = 138,
    diff_name = "鱼雷默认速度（米/秒）",
    enum_name = "BL_TorpedoSpeedBase",
    data = "15",
  },
  [139] = {
    id = 139,
    diff_name = "自律战斗索敌航速档位",
    enum_name = "BL_FleetAutoSearchSpeed",
    data = "3",
  },
  [140] = {
    id = 140,
    diff_name = "自律战斗索敌疲劳百分比阈值",
    enum_name = "BL_FleetAutoSearchFatigueThreshold",
    data = "0.5",
  },
  [141] = {
    id = 141,
    diff_name = "自律战斗战斗航速档位",
    enum_name = "BL_FleetAutoBattleSpeed",
    data = "3",
  },
  [142] = {
    id = 142,
    diff_name = "自律战斗主炮权重",
    enum_name = "BL_FleetAutoMainGunWeight",
    data = "900",
  },
  [143] = {
    id = 143,
    diff_name = "自律战斗副炮权重",
    enum_name = "BL_FleetAutoViceGunWeight",
    data = "900",
  },
  [144] = {
    id = 144,
    diff_name = "自律战斗鱼雷权重",
    enum_name = "BL_FleetAutoTorpedoWeight",
    data = "5000",
  },
  [145] = {
    id = 145,
    diff_name = "自律战斗航空攻击权重",
    enum_name = "BL_FleetAutoAirAttackWeight",
    data = "5000",
  },
  [146] = {
    id = 146,
    diff_name = "自律战斗远距离权重",
    enum_name = "BL_FleetAutoFarRangeWeight",
    data = "0",
  },
  [147] = {
    id = 147,
    diff_name = "自律战斗中距离权重",
    enum_name = "BL_FleetAutoMiddleRangeWeight",
    data = "1000",
  },
  [148] = {
    id = 148,
    diff_name = "自律战斗近距离权重",
    enum_name = "BL_FleetAutoNearRangeWeight",
    data = "40",
  },
  [149] = {
    id = 149,
    diff_name = "自律战斗距离变换间隔CD（秒）",
    enum_name = "BL_FleetAutoRangeSwitchCD",
    data = "1",
  },
  [150] = {
    id = 150,
    diff_name = "自律战斗战斗技能初始CD（秒）",
    enum_name = "BL_FleetAutoSkillBeginCD",
    data = "1",
  },
  [151] = {
    id = 151,
    diff_name = "自律战斗战斗技能间隔CD（秒）",
    enum_name = "BL_FleetAutoSkillCD",
    data = "1",
  },
  [152] = {
    id = 152,
    diff_name = "自律战斗躲避鱼雷持续时间（秒）",
    enum_name = "BL_FleetAutoAvoidTorpedoDuration",
    data = "3",
  },
  [153] = {
    id = 153,
    diff_name = "PVP脱战时间",
    enum_name = "BL_PVP_LeaveBattleTime",
    data = "5",
  },
  [154] = {
    id = 154,
    diff_name = "PVP世界逻辑尺寸系数",
    enum_name = "BL_PVPWorldScale",
    data = "2.75",
  },
  [155] = {
    id = 155,
    diff_name = "PVP最大炮击圈数",
    enum_name = "BL_PVPMainGunTarget",
    data = "3",
  },
  [156] = {
    id = 156,
    diff_name = "PVP鱼雷充能CD",
    enum_name = "BL_PVPTorpedoChargeCD",
    data = "15",
  },
  [157] = {
    id = 157,
    diff_name = "PVP鱼雷发射公共CD",
    enum_name = "BL_PVPTorpedoShootCD",
    data = "0.5",
  },
  [158] = {
    id = 158,
    diff_name = "PVP脱战距离系数",
    enum_name = "BL_PVPLeaveBattle",
    data = "1.5",
  },
  [159] = {
    id = 159,
    diff_name = "NPCAI在玩家QTE时主炮的释放失败几率",
    enum_name = "BL_PlayerQTEAIMainGunFailedOdds",
    data = "0",
  },
  [160] = {
    id = 160,
    diff_name = "NPCAI在玩家QTE时航空攻击的释放失败几率",
    enum_name = "BL_PlayerQTEAIAirAttackGunFailedOdds",
    data = "0",
  },
  [161] = {
    id = 161,
    diff_name = "NPCAI在玩家QTE时鱼雷的释放失败几率",
    enum_name = "BL_PlayerQTEAITorpedoFailedOdds",
    data = "1",
  },
  [162] = {
    id = 162,
    diff_name = "主炮格挡援护的操作持续时间(毫秒)",
    enum_name = "BL_MainGunOriginalDuration",
    data = "5000",
  },
  [163] = {
    id = 163,
    diff_name = "主炮格挡援护的点击最大次数",
    enum_name = "BL_MainGunOriginalMaxClickNum",
    data = "10",
  },
  [164] = {
    id = 164,
    diff_name = "战斗结束使用的摄像机路径名",
    enum_name = "battle_end_camera_path",
    data = "shot/settle_camera",
  },
  [165] = {
    id = 165,
    diff_name = "协防保护基础概率(0-1)",
    enum_name = "BL_OriginalBaseOdds",
    data = "0.037",
  },
  [166] = {
    id = 166,
    diff_name = "敌方舰队剩余总血量百分比",
    enum_name = "BGM_PercentageOfEnemyBloodVolume",
    data = "0.3",
  },
  [167] = {
    id = 167,
    diff_name = "己方舰娘当前炮击战大破数量占舰队人数（不包含拉下舰娘）的百分比",
    enum_name = "BGM_PercentageOfBigBreak",
    data = "0.6",
  },
  [168] = {
    id = 168,
    diff_name = "逻辑血量精度",
    enum_name = "BL_HPPrecision",
    data = "10000000000",
  },

}