//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UFrame_ResourceManagement_GameObjectGetterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UFrame.ResourceManagement.GameObjectGetter), typeof(System.Object));
		L.RegFunction("SetAssetHolder", SetAssetHolder);
		L.RegFunction("Get", Get);
		L.RegFunction("New", _CreateUFrame_ResourceManagement_GameObjectGetter);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUFrame_ResourceManagement_GameObjectGetter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UFrame.ResourceManagement.GameObjectGetter obj = new UFrame.ResourceManagement.GameObjectGetter();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UFrame.ResourceManagement.GameObjectGetter.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAssetHolder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UFrame.ResourceManagement.GameObjectGetter obj = (UFrame.ResourceManagement.GameObjectGetter)ToLua.CheckObject<UFrame.ResourceManagement.GameObjectGetter>(L, 1);
			UFrame.ResourceManagement.AssetHolder arg0 = (UFrame.ResourceManagement.AssetHolder)ToLua.CheckObject<UFrame.ResourceManagement.AssetHolder>(L, 2);
			obj.SetAssetHolder(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Get(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UFrame.ResourceManagement.GameObjectGetter obj = (UFrame.ResourceManagement.GameObjectGetter)ToLua.CheckObject<UFrame.ResourceManagement.GameObjectGetter>(L, 1);
			UnityEngine.GameObject o = obj.Get();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

