//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UFrame_ResourceManagement_AssetGetterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UFrame.ResourceManagement.AssetGetter), typeof(System.Object));
		L.RegFunction("SetAssetHolder", SetAssetHolder);
		L.RegFunction("GetAll", GetAll);
		L.RegFunction("New", _CreateUFrame_ResourceManagement_AssetGetter);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUFrame_ResourceManagement_AssetGetter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UFrame.ResourceManagement.AssetGetter obj = new UFrame.ResourceManagement.AssetGetter();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UFrame.ResourceManagement.AssetGetter.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAssetHolder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UFrame.ResourceManagement.AssetGetter obj = (UFrame.ResourceManagement.AssetGetter)ToLua.CheckObject<UFrame.ResourceManagement.AssetGetter>(L, 1);
			UFrame.ResourceManagement.AssetHolder arg0 = (UFrame.ResourceManagement.AssetHolder)ToLua.CheckObject<UFrame.ResourceManagement.AssetHolder>(L, 2);
			obj.SetAssetHolder(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UFrame.ResourceManagement.AssetGetter obj = (UFrame.ResourceManagement.AssetGetter)ToLua.CheckObject<UFrame.ResourceManagement.AssetGetter>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			object o = obj.GetAll(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

